#spring.application.name=Library Management System
Spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
  application:
    name: lms
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: anushka567